packages:
  - aabha
  - aabha/examples/*
  - eslint-plugin-aabha

autoInstallPeers: true

ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild
  - rollup
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
  - rollup
  - unrs-resolver

strictPeerDependencies: false
